### ISSUE TITLE
Can you please add 0xaB01BAd2C86e24D371A13eD6367bdCa819589C5D to the list of available tokens?

### ISSUE THREAD

**Issue by lukicpa** [skalenetwork/portal#199] opened 2024-03-05 08:40 UTC
It would be nice to update the list of available tokens

https://portal.skale.space/chains/nebula

with new one, recently added, Europa ETH.

**Comment by TheGreatAxios** [comment] 2024-06-14 19:35
Duplicate of https://github.com/skalenetwork/portal/issues/254

**Comment by TheGreatAxios** [comment] 2024-06-18 17:39
Duplicate of https://github.com/skalenetwork/portal/issues/254

**Closed by TheGreatAxios** 2024-06-18 17:39 UTC
Labels: Support
